---
title: "Feeding, Parenting and Immunization"
---

## QCH -- Queensway Carleton Hospital

### Well baby, Jaundice and Breastfeeding Clinic

<abbr title="Queensway Carleton Hospital">QCH</abbr> sees babies in their clinic after your baby goes home. For the first follow up visit, if you do not have a family doctor a you may get booked into their well baby clinic where your baby can be assessed for weight, infant feeding and checked by a doctor. If there is a concern about jaundice, the doctor can book a follow up visit.

<abbr title="Queensway Carleton Hospital">QCH</abbr> offers feeding support for families as well for babies up to 3 weeks after the baby is discharged.

> Book an appointment before you go home call to book at **613-721-2000 x4816**

## Ottawa Public Health

For continued follow up, families that may not have access to a family doctor, Ottawa Public Health (OPH) is helping to provide free support.

<abbr title="Ottawa Public Health">OPH</abbr> offers a variety of services from Covid-19 and flu vaccines, to dental screening, parenting and lactation support and immunizations for school age children and now there are some hubs offering routine vaccinations for children.

> These hubs are drop-in and therefore no appointment is needed.

## Feeding and Parenting Support

These are staffed by a public health nurse and lactation consultant. You can get support with infant feeding, your baby can be weighed, learn ways for your child to be healthy and active, check in with your baby's growth and development, social and emotional development. These are for families with children 0-6 years old.

+-----------------------+---------------------------------------------------------------------------------------+
| Day and Time          | Parenting In Ottawa Drop-in Location                                                  |
+=======================+=======================================================================================+
| Monday                | **South/ Central**                                                                    |
|                       |                                                                                       |
| 1PM-3PM               | Andrew Fleck Children's Services                                                      |
|                       |                                                                                       |
|                       | [2330 Don Reid, Suite 101](https://goo.gl/maps/6uaF3poEiwPf85TMA?coh=178573&entry=tt) |
|                       |                                                                                       |
|                       | Ottawa, ON                                                                            |
+-----------------------+---------------------------------------------------------------------------------------+
| Tuesdays              | **West**                                                                              |
|                       |                                                                                       |
| 12:30-2:30            | Beaverbrook Library                                                                   |
|                       |                                                                                       |
|                       | [2500 Campeau Dr](https://goo.gl/maps/ihbwo3C2TwgikT71A?coh=178573&entry=tt)          |
|                       |                                                                                       |
|                       | Kanata, ON                                                                            |
+-----------------------+---------------------------------------------------------------------------------------+
| Tuesdays              | **East**                                                                              |
|                       |                                                                                       |
| 1:30-3:30             | Vanier Community Center- 2nd floor                                                    |
|                       |                                                                                       |
|                       | Every other week (i.e. March 14, March 26)                                            |
|                       |                                                                                       |
|                       | [270 Marier Ave](https://goo.gl/maps/ZQKUxUhomoKvwjnp9?coh=178573&entry=tt)           |
|                       |                                                                                       |
|                       | Vanier, ON                                                                            |
+-----------------------+---------------------------------------------------------------------------------------+
| Wednesday             | **South/East**                                                                        |
|                       |                                                                                       |
| 1PM-3PM               | AMA Community Center                                                                  |
|                       |                                                                                       |
|                       | [1216 Huntclub Road](https://goo.gl/maps/JjR8qCSe8X2Ue3rW6?coh=178573&entry=tt)       |
|                       |                                                                                       |
|                       | Ottawa, ON                                                                            |
+-----------------------+---------------------------------------------------------------------------------------+
| Thursday              | **East**                                                                              |
|                       |                                                                                       |
| 1PM-3PM               | Orleans Cumberland Community Resource Center                                          |
|                       |                                                                                       |
|                       | [240 Centrum Blvd](https://goo.gl/maps/AGfbCP1VY3jXDfbp6?coh=178573&entry=tt)         |
|                       |                                                                                       |
|                       | Orleans, ON                                                                           |
+-----------------------+---------------------------------------------------------------------------------------+
| Friday                | **West**                                                                              |
|                       |                                                                                       |
| 10AM-12PM             | Bayshore Field House                                                                  |
|                       |                                                                                       |
|                       | [175 Woodridge Cres](https://goo.gl/maps/spJpYP35Y3UvGj4Z7?coh=178573&entry=tt)       |
|                       |                                                                                       |
|                       | Ottawa, ON                                                                            |
+-----------------------+---------------------------------------------------------------------------------------+
| Saturday              | **Central/West**                                                                      |
|                       |                                                                                       |
| 10AM-12:30PM          | Mothercraft                                                                           |
|                       |                                                                                       |
|                       | [475 Evered Ave](https://goo.gl/maps/NhEoH3SLKKg5kakG6?coh=178573&entry=tt)           |
|                       |                                                                                       |
|                       | Ottawa, ON                                                                            |
+-----------------------+---------------------------------------------------------------------------------------+
| Sunday                | **Central/East**                                                                      |
|                       |                                                                                       |
| 10AM-12:30PM          | St Laurent Complex                                                                    |
|                       |                                                                                       |
|                       | [525 Coté St](https://goo.gl/maps/WuziBtC3GGCmgYPB8?coh=178573&entry=tt)              |
|                       |                                                                                       |
|                       | Ottawa, ON                                                                            |
+-----------------------+---------------------------------------------------------------------------------------+

You can also call <abbr title="Ottawa Public Health">QCH</abbr> to speak with a Public Health nurse at **613-580-6744**

-   [Locations and times of drop-ins](https://calendars.ottawapublichealth.ca/PIODropIns/Week)

-   [Breastfeeding support options](https://www.parentinginottawa.ca/en/breastfeeding/breastfeeding-resources-in-ottawa.aspx)

-   [Caring for your new baby](https://www.parentinginottawa.ca/en/babies-and-toddlers/Life-with-a-new-baby.aspx)

## Do you need help with infant feeding?

Speak directly with a Public Health Nurse by calling the <abbr title="Ottawa Public Health">QCH</abbr> Information Line

-   Monday to Friday from 9 am to 4 pm

-   613-PARENTS (**613-727-3687**) (ATS : **613-580-9656**) and choose option 4.

## Parenting in Ottawa Drop-in Clinics

The Parenting In Ottawa drop-ins are located across the City of Ottawa.

Speak, in person, with a Public Health Nurse or lactation consultant about questions that you might have.

-   Get support for infant feeding

-   **Breast pumps are available to borrow for 1-2 weeks**

-   Make sure your child is on track with their growth and development

-   Provides support and information about how to take care of your baby

The program is Free and available to:

-   Expectant parents,

-   Parents and guardians of children aged birth to 6 years of age

Visit [www.parentinginottawa.ca](https://calendars.ottawapublichealth.ca/PIODropIns/Week?Breastfeeding%20and%20Parenting%20Support%20Drop-Ins=Parenting%20in%20Ottawa%20Drop-Ins%20(Breastfeeding%20and%20parenting%20support%20for%20parents%20of%20children%20from%20birth%20to%206%20years)&) to view resources

## Routine Immunizations for Babies and Children

-   Children require immunizations at 2, 4, 6, 12, 15 and 18 months

-   Children then require immunizations between 4 years and 6 years of age

-   These immunization clinics are for families who **do not** have <abbr title="Ontario Health Insurance Plan">OHIP</abbr> or a family doctor.

-   If pregnant can get Tdap (Tetanus, Diptheria and Pertussis) between 28-32 weeks

-   Please bring any immunization records you already have and some kind of identification for you and your children (if available)

> For more information on publicly funded immunizations (free) see [Vaccines through the lifespan](https://www.health.gov.on.ca/en/pro/programs/immunization/docs/immunization_poster_lifespan.pdf)

### Ottawa Public Health -- No <abbr title="Ontario Health Insurance Plan">OHIP</abbr> required

Location and hours:

-   [By appointment- family vaccine clinic](https://reservation.frontdesksuite.ca/oph/routinecommunity/Home/Index?Culture=en&PageId=a5d911ef-1a96-474d-96cf-239ec39c0da6&ShouldStartReserveTimeFlow=False&ButtonId=00000000-0000-0000-0000-000000000000)

For babies, young children or if you are pregnant and need the <abbr title="Tetanus, Diptheria and Pertussis">Tdap</abbr> vaccine (given between 28-32 weeks) please look to the [NEIGHBOURHOOD HEALTH AND WELLNESS LOCATIONS that offer Routine Vaccines.](#0){style="font-size: 11pt;"}

> For questions or to make appointment, call **613-580-6744**

### East Ottawa Kids Clinic -- 4289 Innes Road -- 2nd floor -- **NO** <abbr title="Ontario Health Insurance Plan">OHIP</abbr> REQUIRED

-   Runs immunization clinic **every other Saturday** for children under 18 months

> No Well-Baby visits. Ony immunizations.

-   Request an appointment by emailing [eastottawakidscovidcareclinic\@gmail.com](mailto:eastottawakidscovidcareclinic@gmail.com){.email}

### College Square Medical Care -- <abbr title="Ontario Health Insurance Plan">OHIP</abbr> REQUIRED

-   CALL **613-224-6606** - Appointments offered on Thursday mornings only

-   1980 Baseline Road (Near Algonquin College)

-   For children 9 months or older

-   Immunization assessments and Publicly funded required immunizations

> **There is a \$50 charge for missed appointments**
