---
title: "Find a Community Lactation Consultant (IBCLC)" 
---

The Lactation Consultants listed here are all International Board -- Certified Lactation Consultants (BCLCs), certified by the International Board of Lactation Consultant Examiners. Private consultations with an <abbr title="International Board -- Certified Lactation Consultants">IBCLC</abbr>'S offer the benefit of skilled one-on-one help with breastfeeding in the comfort of your own home, or in the <abbr title="International Board -- Certified Lactation Consultants">IBCLC</abbr>'s office.

------------------------------------------------------------------------

## Ginette Bertrand IA, Bsc inf, BLCLC

Service Perinatal Service Since 1995

West and East Ottawa locations

Visite à domicile/home Visits to Ottawa

Bilingue/bilingual

**(613) 746-9480**

------------------------------------------------------------------------

## [Beth McMillan BA child Studies, IBCLC](https://milkface.com/pages/book-with-beth)

In-office consultations at Milkface, 455 Churchill Ave.

**(613) 596-1170 or (613) 298-6847**

www.bethmcmillanibclc.com

------------------------------------------------------------------------

## Sonya Boersma BN, MSCN, RN, IBCLC

Lactation Care since 2003

West end based. City-wide visits

Consults in-home, in-office, or virtual

\*613-355-1615\*\*

[**sonya\@lactationcare.ca**](mailto:sonya@lactationcare.ca){.email}

------------------------------------------------------------------------

## [Lyne Lacroix IBCLC, RLC](https://www.facebook.com/lynelacroixibclc)

Serving Eastem Ontario (Prescott-Russell, Stormont, Dundas and Glengarry)

Office Consultations

**(613) 632-0797**

------------------------------------------------------------------------

## Sue Theriault Valin BSc, IBCLC

Nepean based, home visits city-wide

Bilingual/bilingue

**(613) 276-7793**

[Suetv.ibclc\@gmail.com](mailto:Suetv.ibclc@gmail.com){.email}

------------------------------------------------------------------------

## [Latch Lactation Consultant](www.latchlactationconsulting.com)

Trish Toompuu RN, IBCLC

West End Office, home Visits City-wide

**613)266-5553**

[latchottawa\@gmail.com](mailto:latchottawa@gmail.com){.email}

[www.latchlactationconsulting.com](https://www.latchlactationconsulting.com/)

------------------------------------------------------------------------

## [Adria MacMartin](https://www.rootedfamily.ca/staff/adria-macmartin)

Infant Feeding Support Services

**613-867-5175**

[AMacMartin66\@gmail.com](mailto:AMacMartin66@gmail.com){.email}

------------------------------------------------------------------------

## Milkface Lactation Services

Jan Chan IBCLC, Britt Pegan IBCLC, Beth McMian BA Child Studies, IBCLC

445 Churchill Ave Nr K1Z

**(613) 596-1170**

------------------------------------------------------------------------
